#!/usr/bin/env bash

TESTS="FDPASS LOCK6 BROWSE MAXFID TORTURE DIR DIR-CREATETIME RW1 RW2 RW3
RW-SIGNING CASE-INSENSITIVE-CREATE WILDDELETE PROPERTIES W2K ERRMAPEXTRACT
IOCTL CHKPATH CHAIN1 WINDOWS-WRITE CLI_ECHO SMB-ANY-CONNECT qpathinfo-bufsize"

# Failing tests:
# LOCK1 LOCK2 LOCK3 LOCK4 LOCK5 LOCK7 LOCK8 LOCK9 UNLINK ATTR TRANS2 RANDOMIPC
# NEGNOWAIT NBENCH NBENCH2 DIR1 DENY1 DENY2 TCON TCONDEV OPEN ASYNC-ECHO
# UID-REGRESSION-TEST ADDRCHANGE MANGLE TRANS2SCAN NTTRANSSCAN UTABLE CASETABLE
# TCON2 FDSESS CHAIN2 LARGE_READX TLDAP BAD-NBT-SESSION IGN-BAD-NEGPROT
# NOTIFY-ONLINE PIDHIGH

# Unsupported tests (will probably never be supported)
# SMB2-BASIC SMB2-NEGPROT SMB2-ANONYMOUS SMB2-SESSION-RECONNECT
# SMB2-TCON-DEPENDENCE SMB2-MULTI-CHANNEL SMB2-SESSION-REAUTH SMB2-FTRUNCATE
# SMB2-DIR-FSYNC OPLOCK-CANCEL OPLOCK1 OPLOCK2 OPLOCK4 POSIX POSIX-APPEND
# POSIX-SYMLINK-ACL POSIX-SYMLINK-EA POSIX-STREAM-DELETE POSIX-OFD-LOCK
# POSIX-MKDIR WINDOWS-BAD-SYMLINK SHORTNAME-TEST OPENATTR XCOPY RENAME
# RENAME-ACCESS OWNER-RIGHTS DELETE DELETE-PRINT DELETE-LN MANGLE1
# MANGLE-ILLEGAL EATEST SESSSETUP_BENCH CHAIN3 NTTRANS-CREATE NTTRANS-FSCTL
# CLI_SPLICE STREAMERROR NOTIFY-BENCH NOTIFY-BENCH2 NOTIFY-BENCH3 CLEANUP1
# CLEANUP2 CLEANUP3 CLEANUP4 WBCLIENT-MULTI-PING PIPE_NUMBER

./samba/bin/smbtorture3 "//${1:-localhost}/public" -U "guest%" $TESTS
