name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:  # Nightly build
    - cron: "15 1 * * *"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
    - name: make
      run: make -j -C src

    - name: Check version output
      id: version
      run: |
        if git describe --exact-match --tags; then
          VERSION=$(git describe --exact-match --tags)
          VERSION=${VERSION/#tumba-/}
          VERSION_OUTPUT=$(./src/tumba_smbd --version)
          if [ "$VERSION_OUTPUT" != "Tumba $VERSION" ]; then
            echo "Wrong version number output:"
            echo " for tag '$(git describe --exact-match --tags)',"
            echo " --version output gave '$VERSION_OUTPUT'"
            false
          fi
        fi

  code_health_checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Install tools
      run: |
        sudo apt update
        sudo apt -q install clang-format iwyu
    - name: Run checks
      run: |
        make -C src fixincludes
        make -C src format
        git diff > formatting-fixes.diff
        if ! grep "" formatting-fixes.diff; then
          rm -f formatting-fixes.diff
        else
          (echo "Formatting errors detected by clang-format. Please run" \
                "\`make fixincludes && make format\` or apply" \
                "formatting-fixes.diff below.";
           echo) >> $GITHUB_STEP_SUMMARY
          false
        fi
    - uses: actions/upload-artifact@v6
      if: '!cancelled()'
      with:
        if-no-files-found: ignore
        name: formatting-fixes.diff
        path: formatting-fixes.diff
